name: Gitpod docker image

on:
  push:
    paths:
      - 'gitpod/**'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'gitpod/**'
  workflow_dispatch:

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub Registry
        if: contains('refs/heads/main', github.ref)
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: gitpod
          push: ${{ (contains('refs/heads/main', github.ref) || 'true') && 'false' }}
          tags: bacluc2/jumpstart-gitpod:latest
          cache-from: type=gha,scope=jumpstart-gitpod
          cache-to: type=gha,scope=jumpstart-gitpod,mode=max
